version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:password@host.docker.internal:5432/vehicle_rental_system_backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend:/backend

  auth:
    build: ./auth
    container_name: auth_app
    ports:
      - "8001:8001"
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://auth_user:auth_password@host.docker.internal:5432/auth_db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./auth:/auth
