"""Created auth tables in schema auth

Revision ID: 0fce299b2c05
Revises: 
Create Date: 2026-04-08 16:30:11.093337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fce299b2c05'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_secret', sa.String(), nullable=False),
    sa.Column('redirect_url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('client_name'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_clients_client_id'), 'clients', ['client_id'], unique=False, schema='auth')
    op.create_table('permissions',
    sa.Column('permissions_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('permissions_id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_permissions_name'), 'permissions', ['name'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_permissions_permissions_id'), 'permissions', ['permissions_id'], unique=False, schema='auth')
    op.create_table('roles',
    sa.Column('roles_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('roles_id'),
    sa.UniqueConstraint('name'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_roles_roles_id'), 'roles', ['roles_id'], unique=False, schema='auth')
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_users_user_id'), 'users', ['user_id'], unique=False, schema='auth')
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth.permissions.permissions_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['auth.roles.roles_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema='auth'
    )
    op.create_table('tokens',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['auth.clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_tokens_access_token'), 'tokens', ['access_token'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_tokens_refresh_token'), 'tokens', ['refresh_token'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_tokens_token_id'), 'tokens', ['token_id'], unique=False, schema='auth')
    op.create_table('users_role',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['auth.roles.roles_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='auth'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_role', schema='auth')
    op.drop_index(op.f('ix_auth_tokens_token_id'), table_name='tokens', schema='auth')
    op.drop_index(op.f('ix_auth_tokens_refresh_token'), table_name='tokens', schema='auth')
    op.drop_index(op.f('ix_auth_tokens_access_token'), table_name='tokens', schema='auth')
    op.drop_table('tokens', schema='auth')
    op.drop_table('role_permissions', schema='auth')
    op.drop_index(op.f('ix_auth_users_user_id'), table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    op.drop_index(op.f('ix_auth_roles_roles_id'), table_name='roles', schema='auth')
    op.drop_table('roles', schema='auth')
    op.drop_index(op.f('ix_auth_permissions_permissions_id'), table_name='permissions', schema='auth')
    op.drop_index(op.f('ix_auth_permissions_name'), table_name='permissions', schema='auth')
    op.drop_table('permissions', schema='auth')
    op.drop_index(op.f('ix_auth_clients_client_id'), table_name='clients', schema='auth')
    op.drop_table('clients', schema='auth')
    # ### end Alembic commands ###
