"""added deposit_amount per vehicle

Revision ID: 212c89665d23
Revises: fcb34e7796f1
Create Date: 2026-04-09 10:55:51.685836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '212c89665d23'
down_revision: Union[str, Sequence[str], None] = 'fcb34e7796f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('deposit_amount', sa.Float(), nullable=False), schema='backend')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'deposit_amount', schema='backend')
    # ### end Alembic commands ###
