"""added otp column to bookings table

Revision ID: 447978356b48
Revises: c4563e4fee62
Create Date: 2026-04-10 17:09:34.570833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '447978356b48'
down_revision: Union[str, Sequence[str], None] = 'c4563e4fee62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('otp', sa.String(), nullable=False), schema='backend')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'otp', schema='backend')
    # ### end Alembic commands ###
