"""removed password_hash column from backend table

Revision ID: 6b574e337089
Revises: 212c89665d23
Create Date: 2026-04-09 14:33:52.198491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b574e337089'
down_revision: Union[str, Sequence[str], None] = '212c89665d23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash', schema='backend')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False), schema='backend')
    # ### end Alembic commands ###
