"""removed the otp and otp_verified from trip table

Revision ID: beef1075df26
Revises: 447978356b48
Create Date: 2026-04-10 17:23:31.772023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beef1075df26'
down_revision: Union[str, Sequence[str], None] = '447978356b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'otp_code', schema='backend')
    op.drop_column('trips', 'otp_verified', schema='backend')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('otp_verified', sa.BOOLEAN(), autoincrement=False, nullable=False), schema='backend')
    op.add_column('trips', sa.Column('otp_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False), schema='backend')
    # ### end Alembic commands ###
