"""removed password_hash column from backend table, this time vendor

Revision ID: c4563e4fee62
Revises: 6b574e337089
Create Date: 2026-04-09 17:58:29.397563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4563e4fee62'
down_revision: Union[str, Sequence[str], None] = '6b574e337089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'password_hash', schema='backend')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False), schema='backend')
    # ### end Alembic commands ###
