"""Created backend tables

Revision ID: fcb34e7796f1
Revises: 
Create Date: 2026-04-08 19:00:59.685219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcb34e7796f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('location_id'),
    schema='backend'
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    schema='backend'
    )
    op.create_table('vendors',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('vendor_id'),
    schema='backend'
    )
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('fuel_type', sa.String(length=50), nullable=False),
    sa.Column('seating_capacity', sa.Integer(), nullable=False),
    sa.Column('price_per_hour', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['backend.locations.location_id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['backend.vendors.vendor_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id'),
    schema='backend'
    )
    op.create_index(op.f('ix_backend_vehicles_vehicle_id'), 'vehicles', ['vehicle_id'], unique=False, schema='backend')
    op.create_table('bookings',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('vendor_payout', sa.Float(), nullable=False),
    sa.Column('security_deposit', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['backend.users.user_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['backend.vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('booking_id'),
    schema='backend'
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['backend.users.user_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['backend.vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('review_id'),
    schema='backend'
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['backend.bookings.booking_id'], ),
    sa.PrimaryKeyConstraint('payment_id'),
    sa.UniqueConstraint('transaction_id'),
    schema='backend'
    )
    op.create_table('trips',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('start_time_actual', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time_actual', sa.DateTime(timezone=True), nullable=True),
    sa.Column('otp_code', sa.String(length=10), nullable=False),
    sa.Column('otp_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['backend.bookings.booking_id'], ),
    sa.PrimaryKeyConstraint('trip_id'),
    schema='backend'
    )
    op.create_table('damage_reports',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('extra_charge', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['backend.trips.trip_id'], ),
    sa.PrimaryKeyConstraint('report_id'),
    schema='backend'
    )
    op.create_table('vehicle_checks',
    sa.Column('check_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('uploaded_by', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['backend.trips.trip_id'], ),
    sa.PrimaryKeyConstraint('check_id'),
    schema='backend'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_checks', schema='backend')
    op.drop_table('damage_reports', schema='backend')
    op.drop_table('trips', schema='backend')
    op.drop_table('payments', schema='backend')
    op.drop_table('reviews', schema='backend')
    op.drop_table('bookings', schema='backend')
    op.drop_index(op.f('ix_backend_vehicles_vehicle_id'), table_name='vehicles', schema='backend')
    op.drop_table('vehicles', schema='backend')
    op.drop_table('vendors', schema='backend')
    op.drop_table('users', schema='backend')
    op.drop_table('locations', schema='backend')
    # ### end Alembic commands ###
